apiVersion: v2
name: resume-lambda-go
description: A Helm chart for deploying Go Lambda services
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - lambda
  - aws
  - serverless
  - golang
home: https://github.com/marcstreeter/resume-lambda-go/
sources:
  - https://github.com/marcstreeter/resume-lambda-go/
maintainers:
  - name: Marc Streeter
    email: mstreeter@gmail.com